reside-46: blog post on deferring errors
reside-ic/reside-ic.github.io pull request #22
Opened 2019-08-08 08:39 UTC by richfitz

2019-08-08 09:43 UTC, weshinsley requested changes
One typo! But this is really cool. A couple of thoughts - not sure if they are worth including:

1. This is especially useful if there is a large upfront delay (eg, read large files), before it gets to the code that fails. The stochastic import is a good example where I'm sure I had times of iteratively fixing the only reported error, with a file-read delay each time...

2. And I suppose at times you might be unlucky and have an error avalanche where all the later errors go away if you fix the first one... So there's a small art of choosing when to defer and when to bail out.

2019-08-08 09:43 UTC, weshinsley commented on content/blog/deferring-errors.md
> +
Hurrah, a typo! involkes

2019-08-08 12:44 UTC, richfitz commented on content/blog/deferring-errors.md
> +
fixed, along with some other typos :see_no_evil:

2019-08-09 08:39 UTC, weshinsley approved these changes
Looks great to me!

2019-08-09 09:55 UTC, r-ash approved these changes
Really interesting stuff and great write up. 

Should we link the blog post from the repo too?

2019-08-09 10:19 UTC, richfitz commented
Good idea on the linking @r-ash

2019-08-09 10:20 UTC, merged