Add separate naomi project page
reside-ic/reside-ic.github.io pull request #36
Opened 2020-02-03 14:57 UTC by r-ash

This PR will

* Move `projects` article to be landing page of projects section
* Add a new page for `naomi`

I'm expecting to update the png of the poster when we have settled on the final version. I should probably compress this too? 1MB is quite big for an image on a web page?

2020-02-03 15:14 UTC, richfitz requested changes

2020-02-03 15:14 UTC, richfitz commented on content/projects/_index.md
> +### [Naomi](/projects/naomi)
This is too subtle in the page.  Something like `see the [project page][/projects/naomi]` for more information, though `[naomi]` would probably work for the link

2020-02-03 15:14 UTC, richfitz commented on content/projects/naomi.md
> +A web interface for a model estimating various HIV epidemic indicators at a regional level. For use by
We should link to Jeff somewhere here if he has a web presence. I think the poster would be better displayed as a thumbnail linking through to a pdf?

2020-02-03 15:14 UTC, richfitz commented on content/projects/naomi.md
> +countries in association with UNAIDS. The app is comprised of:
Can we say "this was used in workshops with UNAIDS in December 2019-January 2020, with ongoing direct use by countries" to give a better indication of the use.  Do we want to get Jeff to provide us with a 2-sentence blurb about the science too?

2020-02-03 15:18 UTC, hillalex commented on content/projects/naomi.md
> +Presented at a poster [RSLondonSouthEast](https://rslondon.ac.uk/) on 6th February
"at" -> "as"? re image, better to just link it as a pdf than embed as a png.

2020-02-04 15:21 UTC, r-ash commented
Still waiting for some sentences from Jeff and to see if he wants us to link to his twitter or imperial bio or something

2020-02-04 16:19 UTC, richfitz approved these changes
Suggestions, but otherwise LGTM.  I'd be happy to merge and deploy, then add Jeff's comments when he has time to send them

2020-02-04 16:19 UTC, richfitz commented on content/projects/naomi.md
> +   * [web application database](https://github.com/mrc-ide/hint-db)
"web application database" -> "a Postgres database for the Kotlin web app"

2020-02-04 16:19 UTC, richfitz commented on content/projects/naomi.md
> +* [a Kotlin web server](https://github.com/mrc-ide/hint)
"web server" or "web app"?

2020-02-05 12:15 UTC, merged